@startuml
Client -> IssueBuilderInstance: gimme new

Client -> IssueBuilderInstance: setFileName("affected.file")
Client -> IssueBuilderInstance: setLineStart(0)

IssueBuilderInstance --> IssueInstance: new (pathName, "affected.file", 0, lineEnd, columnStart, columnEnd, lineRanges, category, type, packageName, moduleName, severity,message, description, origin, reference, fingerprint, additionalProperties, id)

IssueBuilderInstance -> Client: IssueInstance

@enduml